# Generated by Django 4.2.16 on 2024-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimatologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_type', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('tiff_file', models.FileField(upload_to='tiff_images/')),
            ],
        ),
    ]
