# Generated by Django 4.2.16 on 2024-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_verification', '0004_gcmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcmimage',
            name='method',
            field=models.CharField(default='Regression', max_length=100),
        ),
        migrations.AlterField(
            model_name='gcmimage',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
