# Generated by Django 4.2.16 on 2024-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_verification', '0005_gcmimage_method_alter_gcmimage_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('lead_time', models.CharField(max_length=100)),
                ('roc_type', models.CharField(max_length=100)),
                ('tiff_file', models.FileField(upload_to='skill_images/')),
            ],
        ),
    ]
