# Generated by Django 4.2.16 on 2024-09-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal_verification', '0006_skillimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillimage',
            name='data_type',
            field=models.CharField(default='Raw Data', max_length=100),
        ),
        migrations.AddField(
            model_name='skillimage',
            name='parameter',
            field=models.CharField(default='Precipitation', max_length=100),
        ),
    ]
