# Generated by Django 4.2.16 on 2024-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seasonal_verification", "0007_skillimage_data_type_skillimage_parameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=100)),
                ("season", models.CharField(blank=True, max_length=100)),
                ("image", models.FileField(upload_to="reference_image/")),
            ],
        ),
    ]
